
-- This makes sure that foreign_key constraints are observed and that errors will be thrown for violations
PRAGMA foreign_keys=ON;

BEGIN TRANSACTION;

-- STUDENT ACCOUNTS
CREATE TABLE IF NOT EXISTS studentAccounts
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,  
    full_name TEXT NOT NULL,
    email_address TEXT NOT NULL,
    account_password TEXT NOT NULL,
    account_active BOOLEAN NOT NULL
);

-- INSTRUCTOR ACCOUNTS
CREATE TABLE IF NOT EXISTS instructorAccounts
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,  
    full_name TEXT NOT NULL,
    email_address TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    account_password TEXT NOT NULL,
    age TEXT NOT NULL,
    gender TEXT NOT NULL,
    skill TEXT NOT NULL, 
    language_medium TEXT NOT NULL, 
    experience TEXT NOT NULL, 
    lesson_size TEXT NOT NULL,
    lesson_type TEXT NOT NULL,
    lesson_location TEXT NOT NULL, 
    fees_range TEXT NOT NULL, 
    bio TEXT NOT NULL, 
    account_active BOOLEAN NOT NULL
);

-- INSERT SOME DATA INTO INSTRUCTOR ACCOUNTS
INSERT INTO instructorAccounts (full_name, email_address, phone_number, account_password, age, gender, skill, language_medium, 
            experience, lesson_size, lesson_type, lesson_location, fees_range, bio, account_active) VALUES 
            ('Michael Lee',
            'michael.lee@gmail.com',
            '82345678',
            '1111@44',
            '27',
            'Male',
            'Swimming',
            'English',
            '1 - 2 years',
            'One-to-one',
            'Face-to-face',
            'Singapore',
            '$30 - $50',
            'I am an experienced swimming teacher with a specialization in Biology. I have been teaching for 2 years at a junior college.',
            0),
            ('Sarah Brown',
            'sarah.brown99@gmail.com',
            '98765432',
            'P@ssw0rd!S@rah',
            '35',
            'Female',
            'Piano',
            'Malay',
            '5 - 10 years',
            'One-to-one & Group',
            'Online & Face-to-face',
            'Central',
            '$50 - $70',
            'I have been teaching piano for 7 years. l graduated with a Bachelor degree in Music from LASALLE College of the Arts. I enjoy inspiring my students to express themselves through various piano notes.',
            0),
            ('Mei Yan Koh',
            'meiyan53@gmail.com',
            '94567890',
            'M4ie3detest',
            '25',
            'Female',
            'Badminton',
            'Mandarin',
            'Less than a year',
            'One-to-one & Group',
            'Face-to-face',
            'North-East',
            'Less than $30',
            'I am passionate about team play and badminton is my favorite hobby.',
            0),
            ('Hui Ling Lim',
            'hui.ling87@gmail.com',
            '87654321',
            'hui65L!ng',
            '37',
            'Male',
            'Badminton',
            'Cantonese',
            '5 - 10 years',
            'One-to-one & Group',
            'Face-to-face',
            'Singapore',
            '$30 - $50',
            'I have been teaching Badminton for 10 years at a junior college. I am passionate about making badminton lessons enjoyable.',
            0),
            ('John Smith',
            'smith.j12@gmail.com',
            '87788991',
            'sM!th993',
            '23',
            'Male',
            'Guitar',
            'English',
            '1 - 2 years',
            'One-to-one & Group',
            'Online & Face-to-face',
            'North-East',
            'Less than $30',
            'I have been teaching Guitar for 2 years. I am passionate about music production.',
            0),
            ('Kian Seng Wong',
            'ksw007@gmail.com',
            '87788992',
            'kian357@sw',
            '40',
            'Female',
            'Painting',
            'Mandarin',
            'More than 10 years',
            'Group',
            'Face-to-face',
            'North',
            '$70 - $100',
            'I have been teaching Painting for 10 years at a junior college. I graduated with a Bachelor degree in Fine Arts from LASALLE College of the Arts.I enjoy inspiring my students to express themselves through various artistic mediums.',
            0),
            ('David Martinez',
            'davidm66@gmail.com',
            '87755693',
            'dv95@T!st',
            '23',
            'Male',
            'Football',
            'English',
            '3 - 4 years',
            'One-to-one & Group',
            'Face-to-face',
            'Singapore',
            'Less than $30',
            'I am a professional footballer who plays as a forward for the national team of Singapore. Born and raised in Singapore,I began my career at a young age, showcasing exceptional talent on the field. ',
            0),
            ('Emily Johnson',
            'emily.js52@gmail.com',
            '87755697',
            'em@ILj52',
            '26',
            'Female',
            'Hockey',
            'English',
            '3 - 4 years',
            'Group',
            'Face-to-face',
            'West',
            '$50 - $70',
            'I am a veteran goalkeeper with a wealth of experience in field hockey.I have been a stalwart presence in the net for my club and country for over 2 years. ',
            0),
            ('Cheng Hock Ng',
            'cheng.ng1357@gmail.com',
            '87755701',
            'ch@ngN!g',
            '30',
            'Female',
            'Dance',
            'Cantonese',
            '3 - 4 years',
            'One-to-one & Group',
            'Online & Face-to-face',
            'Singapore',
            '$70 - $100',
            'I am a versatile dancer proficient in multiple styles, including salsa, bachata, and tango.I have competed in international dance competitions and have won numerous awards for my skill and artistry. ',
            0),
            ('Mia Anderson',
            'mia.And55@gmail.com',
            '85437499',
            '22222222',
            '38',
            'Female',
            'Painting',
            'English',
            '5 - 10 years',
            'Group',
            'Face-to-face',
            'Central',
            '$50 - $70',
            'I am a passionate painter born and raised in Singapore. With a deep love for nature and vibrant colors, I draw inspiration from the lush landscapes of my homeland. My artistic journey began at a young age, and I honed my skills through formal training at the Singapore Art Academy. My work often explore themes of identity, cultural diversity, and the beauty of everyday life. My paintings have been exhibited in various galleries across Singapore and have garnered acclaim for their expressive brushwork and captivating use of color.' ,
            0),
            ('Tan Ah Beng',
            'tan1998@gmail.com',
            '88992233',
            '11111114',
            '28',
            'Male',
            'Guitar',
            'Mandarin',
            '1 - 2 years',
            'One-to-one & Group',
            'Online & Face-to-face',
            'Singapore',
            'Less than $30',
            'My journey with the guitar began at the age of 10 when I received my first acoustic guitar as a birthday gift from my parents. Since then, I have dedicated myself to mastering the instrument, drawing inspiration from a wide range of musical genres including rock, blues, jazz, and classical.My passion for music led me to pursue a degree in Music Performance from the renowned Berklee College of Music in Boston. Throughout my career, I have performed with various bands and artists, both locally and internationally, showcasing my exceptional skill and versatility on the guitar.', 
            0),
            ('Sophia Davis',
            'sophia69@gmail.com',
            '87129733',
            '11111115',
            '32',
            'Female',
            'Swimming',
            'English,Malay',
            '5 - 10 years',
            'One-to-one',
            'Face-to-face',
            'East',
            '$30 - $50',
            'I joined my local swimming team as a child and quickly demonstrated my talent and determination in the pool. Over the years,I have competed in numerous swimming competitions at the regional, national, and international levels.My specialty lies in sprint events, where my explosive speed and powerful strokes set me apart from the competition.',
            0),
            ('Wong Wei Xiang',
            'wei.wong@gmail.com',
            '87222291',
            '11111119',
            '21',
            'Male',
            'Football',
            'Chinese',
            'Less than a year',
            'One-to-one & Group',
            'Online & Face-to-face',
            'Singapore',
            'Less than $30',
            'I began playing in local youth leagues, where my natural athleticism and technical skill quickly caught the attention of coaches and scouts.My dedication to my craft led me to join the youth academy of a prominent Premier League club, where I honed my skills and rose through the ranks. My hard work paid off when I earned a spot on the first team, making my professional debut at the age of 18.',
            0),
            ('Lim Hui Shan',
            'lim56@gmail.com',
            '89332314',
            '22221232',
            '24',
            'Female',
            'Hockey',
            'Chinese,English',
            '1 - 2 years',
            'Group',
            'Face-to-face',
            'East',
            'Less than $30',
            'My journey in hockey took me through the ranks of youth leagues and provincial championships, where I consistently stood out as a top performer. My determination and commitment to excellence earned me a scholarship to play collegiate hockey in Singapore, where I excelled both academically and athletically. Today, I continues to pursue my passion for hockey as a professional player.',
            0),
            ('William Clark',
            'clark77@gmail.com',
            '83023126',
            'Dance123!',
            '25',
            'Male',
            'Dance',
            'English',
            '3 - 4 years',
            'One-to-one & Group',
            'Online',
            'Singapore',
            '$30 - $50',
            'I am a passionate dancer with over a decade of experience in various dance styles including ballet, contemporary, and hip-hop.I began my dance journey at the age of 5 and have since trained extensively under renowned choreographers and instructors.I enjoy teaching dance classes, choreographing routines, and inspiring others to discover the joy of dance.',
            0),
            ('Benjamin Taylor',
            'benjamintaylor@gmail.com',
            '98765431',
            'Piano0934!',
            '40',
            'Male',
            'Piano',
            'English',
            'More than 10 years',
            'One-to-one & Group',
            'Online & Face-to-face',
            'West',
            'More than $100',
            'I am a highly skilled pianist with a passion for music that spans over 15 years.I began playing the piano at the age of 5 and quickly showed exceptional talent and dedication to my craft.My musical journey have taken me through formal training at prestigious music schools and conservatories, where I studied classical piano repertoire under world-renowned pianists. Throughout my career, I have performed in solo recitals, chamber music concerts, and orchestral performances, captivating audiences with my expressive interpretations and virtuosic technique.',
            0),
            ('Lily Chen',
            'lilychen@gmail.com',
            '87654322',
            'Paint965!',
            '33',
            'Female',
            'Painting',
            'Chinese,English',
            '5 - 10 years',
            'One-to-one',
            'Online',
            'Singapore',
            '$50 - $70',
            'I pursued formal art education at the prestigious Central Academy of Fine Arts, where I honed my skills in various painting techniques and styles. My artistic journey have taken me across the globe, allowing me to draw inspiration from diverse landscapes and cultures. My paintings often reflect my love for nature, with a focus on capturing the beauty and tranquility of landscapes and seascapes.',
            0),
            ('Ng Chee Kiat',
            'ngcheekiat@gmail.com',
            '87651357',
            'Guitar123!',
            '29',
            'Male',
            'Guitar',
            'English',
            '5 - 10 years',
            'One-to-one & Group',
            'Online & Face-to-face',
            'East',
            '$30 - $50',
            'I have dedicated myself to mastering the instrument, exploring various genres ranging from rock and blues to jazz and country.My musical journey has taken me from local gigs at small venues to performing on stages across the country, captivating audiences with my soulful melodies and electrifying solos.I am also a passionate music educator, offering private lessons and workshops to aspiring guitarists looking to hone their craft.',
            0),
            ('Rachel Wong',
            'rachelwong@gmail.com',
            '88553211',
            'Swim123!88',
            '22',
            'Female',
            'Swimming',
            'English',
            '1 - 2 years',
            'Group',
            'Face-to-face',
            'North',
            'Less than $30',
            'My love for swimming began at an early age when I first dipped my toes in the ocean. Since then, I have spent countless hours training in pools and open water, refining my technique and building my endurance. My hard work and dedication have paid off, as I have competed in numerous swimming competitions at the regional, national, and international levels. My specialties include freestyle and butterfly events, where I showcase my speed and agility in the water.',
            0),
            ('Ethan Thompson',
            'ethan1990@gmail.com',
            '83210897',
            'ftball224!',
            '32',
            'Male',
            'Football',
            'English',
            'More than 10 years',
            'One-to-one & Group',
            'Face-to-face',
            'Central',
            '$50 - $70',
            'Over the years, I have played for several clubs, showcasing my versatility as a midfielder and my ability to dictate play on the field.My leadership qualities and tactical awareness have earned me the respect of teammates and opponents alike, making me a valuable asset to any team. Off the field, I am actively involved in charitable initiatives, using my platform as a footballer to give back to my community and support causes close to my heart.',
            0),
            ('Kevin Tan',
            'kevintan@gmail.com',
            '8765092',
            'Shuttle123!',
            '22',
            'Male',
            'Badminton',
            'English,Mandarin,Chinese',
            '1 - 2 years',
            'One-to-one & Group',
            'Face-to-face',
            'North-East',
            '$30 - $50',
            'I am a skilled badminton player with a passion for the sport that spans over a decade. Hailing from Kuala Lumpur, Malaysia,My love for badminton began at a young age when I first picked up a racket at my local community center. Since then,I have dedicated myself to mastering the game, training rigorously and competing in various tournaments at the regional and national levels.',
            0),
            ('Olivia Williams',
            'olivia33@gmail.com',
            '98345678',
            'Hockey993!',
            '29',
            'Male',
            'Hockey',
            'English',
            '5 - 10 years',
            'One-to-one',
            'Face-to-face',
            'West',
            '$50 - $70',
            'I am actively involved in promoting youth hockey programs and advocating for gender equality in sports.I am passionate about using my platform as an athlete to inspire others and make a positive impact in my community.',
            0),
            ('Maria Garcia',
            'mariagarcia7@gmail.com',
            '99303412',
            'magar456!',
            '26',
            'Female',
            'Dance',
            'English,Malay',
            '1 - 2 years',
            'One-to-one & Group',
            'Online & Face-to-face',
            'East',
            '$30 - $50',
            'I am a versatile dancer with a decade of experience in various dance styles. My passion for dance was sparked at a young age when I attended my first ballet class. Since then, I have trained extensively in ballet, contemporary, jazz, and flamenco, developing a unique and expressive dance style that blends elements from different genres.',
            0),
            ('Daniel',
            'daniel@gmail.com',
            '87702345',
            'poain432',
            '31',
            'Female',
            'Piano',
            'English,Korean',
            '5 - 10 years',
            'One-to-one & Group',
            'Online',
            'Singapore',
            '$50 - $70',
            'My musical repertoire spans a wide range of styles and periods, from Baroque and Classical to Romantic and Contemporary. In addition to my solo career, I am also a passionate chamber musician, collaborating with esteemed artists and ensembles to bring chamber music to new heights.',
            0)
            ;

COMMIT;

